base_url = "https://j-ito0625.github.io"
title = "Junsei Ito | 伊藤 潤成"
description = "Junsei Ito's personal website"
default_language = "ja"

compile_sass = false
build_search_index = false
generate_feeds = false

[extra]
author = "Junsei Ito"
email = "distinction0625 [at] moegi.waseda.jp"
github = "https://github.com/j-ito0625"
google_analytics = "G-CZ7Z12S44E"
google_site_verification = "ruQzK2Z-YDg7G7Zcb4bSZNGIAZ9zVVRtsld9nm8AOYo"
